### ISSUE TITLE
how to set silent=true?

### ISSUE THREAD

**Issue by didw** [clementfarabet/lua---ffmpeg#13]
Thank you for the good tools, it's very helpful to handle video files.
There is one little thing that makes me annoying.
When I use ffmpeg, there are so many log messages.
I want to reduce log messages. I saw the code and found that if silent=true then it would work. But I don't know how to set silent=true. Can you help me with that?

**Comment by soumith** [comment]
vid = ffmpeg.Video{path='path/to/some/video.mpg', silent=true}

**Comment by didw** [comment]
thank you very much!

2016년 2월 12일 (금) 13:34, Soumith Chintala <notifications@github.com>님이 작성:
